### ISSUE TITLE
没有找到特征文件

### ISSUE THREAD

**Issue by JoinBelieve** [18601949127/DiDiCallCar#7]
Environment.getExternalStorageDirectory() + "/featurevector/traindata/"
下没有文件

**Comment by 18601949127** [comment]
En 训练出来的文件是要放进手机里面才可以方便手机系统作对比，你需要的话我回去找一下发给你




------------------ 原始邮件 ------------------
发件人: "JoinBelieve"<notifications@github.com>;
发送时间: 2019年10月10日(星期四) 下午2:06
收件人: "18601949127/DiDiCallCar"<DiDiCallCar@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [18601949127/DiDiCallCar] 没有找到特征文件 (#7)




Environment.getExternalStorageDirectory() + "/featurevector/traindata/"
 下没有文件

**Comment by JoinBelieve** [comment]
谢谢，问题解决了
